### ISSUE TITLE
cannot run script

### ISSUE THREAD

**Issue by oxycantha** [hanzov69/discord-apple-music#1]
hey! i'm using catalina, and i tried running the script and it worked at first, but then it stopped. when i tried running it again i got this error:
> pypresence.exceptions.ServerError: Child "activity" fails because child "state" fails because "state" is not allowed to be empty

any ideas? thanks!

**Comment by hanzov69** [comment]
I ran in to this myself on Thursday. I started to investigate and it's the AppleScript (of all things!?) failing. 

AppleScript now returns this:

> error "Can’t make «constant ePlSkPSS» into type boolean." number -1700 from «constant ****kPSS» to boolean

Looking in to it, it seems that for some reason, the `player state` evaluation suddenly causes problems? I've rearranged the logic a bit and it seems to be working again.
